[build]
target = "aarch64-unknown-linux-gnu"

[env]
CMAKE_SYSTEM_NAME="Linux"
TARGET="aarch64-linux-gnu"
TARGET_AR="aarch64-linux-gnu-ar"
TARGET_CC="aarch64-linux-gnu-gcc"
TARGET_CXX="aarch64-linux-gnu-g++"
TARGET_RANLIB="aarch64-linux-gnu-ranlib"
TARGET_CPP="aarch64-linux-gnu-cpp"
TARGET_LD="aarch64-linux-gnu-ld"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"